# fly.toml app configuration file generated for postrify-backend on 2024-09-18T19:00:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'postrify-backend'
primary_region = 'mad'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512MB'
  cpu_kind = 'shared'
  cpus = 1

[env]
    JAVA_TOOL_OPTIONS = "-Xmx400m"