name: Deploy Backend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: postrify-backend
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Set Fly.io Secrets
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl secrets set SPRING_DATASOURCE_URL="${{ secrets.SPRING_DATASOURCE_URL }}"
          flyctl secrets set SPRING_DATASOURCE_USERNAME="${{ secrets.SPRING_DATASOURCE_USERNAME }}"
          flyctl secrets set SPRING_DATASOURCE_PASSWORD="${{ secrets.SPRING_DATASOURCE_PASSWORD }}"

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only
